#!/bin/zsh

# zinit bootstrap
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git"
fi
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# zinit annex
zinit light-mode for zdharma-continuum/zinit-annex-bin-gem-node
zinit light-mode for zdharma-continuum/zinit-annex-patch-dl

# completion
setopt noautomenu
fpath=(~/.zsh/completion /usr/share/zsh/vendor-completions $fpath)
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
	compinit -i;
else
	compinit -C;
fi

# History
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# misc
bindkey \^U backward-kill-line

# Themes
export STARSHIP_CONFIG=~/.config/starship/config.toml
zinit lucid from"gh-r" as"null" for completions atpull"%atclone" atclone"starship completions zsh > _starship" sbin"**/starship" @starship/starship
eval "$(starship init zsh)"

# Autojump
export _ZO_FZF_OPTS="$FZF_DEFAULT_OPTS --layout=reverse --height=30%"
zinit lucid from"gh-r" as"null" for completions sbin"**/zoxide" @ajeetdsouza/zoxide
eval "$(zoxide init zsh)"

# FZF
export FZF_DEFAULT_COMMAND='fd --type f --color never'
export FZF_DEFAULT_OPTS='--color=bg+:-1,bg:-1 --preview-window=0 --no-separator --prompt="❯ " --pointer=">"'
export FZF_CTRL_T_COMMAND='fd --type f --color never'
export FZF_ALT_C_COMMAND='fd --type d --color never'
zinit lucid from"gh-r" as"null" for completions dl"https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh -> _fzf" sbin"**/fzf" @junegunn/fzf
zinit for https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh

# Tools
zinit lucid from"gh-r" as"null" for completions dl"https://raw.githubusercontent.com/dbrgn/tealdeer/main/completion/zsh_tealdeer -> _tldr" sbin"**/tealdeer* -> tldr" @dbrgn/tealdeer
zinit lucid from"gh-r" as"null" for completions atload"alias di='delta --side-by-side'" dl"https://raw.githubusercontent.com/dandavison/delta/master/etc/completion/completion.zsh -> _delta" sbin"**/delta" @dandavison/delta
zinit lucid from"gh-r" as"null" for completions atload"alias ls=lsd" cp"**/autocomplete/_lsd -> _lsd" @lsd-rs/lsd
zinit lucid from"gh-r" as"null" for completions dl"https://raw.githubusercontent.com/bootandy/dust/master/completions/_dust -> _dust" sbin"**/dust" @bootandy/dust
zinit lucid from"gh-r" as"null" for sbin"**/duf" @muesli/duf
zinit lucid from"gh-r" as"null" for completions cp"**/autocomplete/_fd -> _fd" sbin"**/fd" @sharkdp/fd
zinit lucid from"gh-r" as"null" for completions cp"**/autocomplete/bat.zsh -> _bat" sbin"**/bat" @sharkdp/bat
zinit lucid from"gh-r" as"null" for completions cp"**/complete/_rg -> _rg" sbin"**/rg" @burntsushi/ripgrep
zinit lucid from"gh-r" as"null" for completions atpull"%atclone" atclone"procs --gen-completion zsh" sbin"**/procs" @dalance/procs
zinit lucid from"gh-r" as"null" for completions atpull"%atclone" atclone"yq shell-completions zsh > _yq" sbin"**/yq* -> yq" @mikefarah/yq
zinit lucid from"gh-r" as"null" for sbin"**/jq* -> jq" @jqlang/jq
zinit lucid from"gh-r" as"null" for sbin"**/tokei* -> tokei" @xampprocky/tokei

# Awesome
# zinit light "jeffreytse/zsh-vi-mode"
zinit light "zsh-users/zsh-completions"
zinit light "zsh-users/zsh-autosuggestions"
zinit light "zsh-users/zsh-syntax-highlighting"
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=green'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=green'

# vim: sw=2 ts=2 et
