#!/bin/zsh

if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
else
  source ~/.zplug/init.zsh
fi

# completion
setopt noautomenu
fpath=(~/.zsh/completion /usr/share/zsh/vendor-completions $fpath)
autoload -Uz compinit && compinit -i

# History
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# misc
bindkey \^U backward-kill-line

# Themes
export STARSHIP_CONFIG=~/.config/starship/config.toml
zplug "starship/starship", from:gh-r, as:command, rename-to:starship, use:"*x86_64*linux*musl*"
eval "$(starship init zsh)"

# Tools
zplug "stedolan/jq", from:gh-r, as:command, rename-to:jq, use:"*linux64*"
zplug "BurntSushi/ripgrep", from:gh-r, as:command, rename-to:rg, use:"*x86_64*linux*musl*"
zplug "dbrgn/tealdeer", from:gh-r, as:command, rename-to:tldr, use:"*linux*x86_64*musl"
zplug "sharkdp/fd", from:gh-r, as:command, rename-to:fd, use:"*x86_64*linux*musl*"
zplug "sharkdp/bat", from:gh-r, as:command, rename-to:bat, use:"*x86_64*linux*musl*"
zplug "dandavison/delta", from:gh-r, as:command, rename-to:delta, use:"*x86_64*linux*musl*"
zplug "Peltoche/lsd", from:gh-r, as:command, rename-to:lsd, use:"*x86_64*linux*musl*"
zplug "bootandy/dust", from:gh-r, as:command, rename-to:dust, use:"*x86_64*linux*musl*"
zplug "muesli/duf", from:gh-r, as:command, rename-to:duf, use:"*linux*x86_64*"
zplug "dalance/procs", from:gh-r, as:command, rename-to:procs, use:"*x86_64*linux*"

# FZF
export FZF_DEFAULT_COMMAND='fd --type f --color never'
export FZF_DEFAULT_OPTS='--color=bg+:-1,bg:-1 --preview-window=0 --no-separator'
export FZF_CTRL_T_COMMAND='fd --type f --color never'
export FZF_ALT_C_COMMAND='fd --type d --color never'
zplug "junegunn/fzf", hook-build:"sh -x install", use:"shell/*.zsh"

# J
export _ZO_FZF_OPTS="$FZF_DEFAULT_OPTS --layout=reverse --height=30%"
zplug "ajeetdsouza/zoxide", from:gh-r, as:command, rename-to:zoxide, use:"*x86_64*linux*musl*"
eval "$(zoxide init zsh)"

# Awesome
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"

# Install plugins if there are plugins that have not been installed, low performance!
# if ! zplug check; then
#   printf "Install? [y/N]: "
#   if read -q; then
#     echo; zplug install
#   fi
# fi

# Then, source plugins and add commands to $PATH
zplug load #--verbose

# vim: sw=2 ts=2 et
