format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

# command_timeout = 1000

[username]
format = "[$user]($style)"
style_user = "bright-black bold"
style_root = "red bold"
disabled = false
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false
ssh_symbol = "@"
style = "bright-black"
disabled = false

[directory]
truncation_length = 100
truncate_to_repo = false
read_only = ""
style = "blue"

[character]
format = "$symbol "
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "bright-black"

[git_commit]
format = "[$hash($tag)]($style)"
style = "bright-black"
tag_symbol = " tag:"
tag_disabled = false

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bright-black)( $ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "≡"
diverged = "⇡⇣"
ahead = "⇡"
behind = "⇣"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[cmd_duration]
format = "[( $duration)]($style)"
style = "yellow"

[python]
format = "[($virtualenv )]($style)"
style = "bright-black"
