format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$python\
$character"""

[username]
format = "[$user]($style)"
style_user = "bright-black bold"
style_root = "red bold"
disabled = false
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false
ssh_symbol = "@"
style = "bright-black"
disabled = false

[directory]
truncation_length = 100
truncate_to_repo = false
read_only = ""
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "≡"
diverged = "⇡⇣"
ahead = "⇡"
behind = "⇣"

[cmd_duration]
format = "[($duration)]($style)"
style = "yellow"
show_milliseconds = true
min_time = 0

[python]
format = "[($virtualenv )]($style)"
style = "bright-black"
